# Generated by Django 3.0.5 on 2020-04-27 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20200427_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 13, 55, 39, 410168)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manag_level',
            field=models.CharField(max_length=2),
        ),
    ]
