# Generated by Django 3.0.5 on 2020-04-28 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20200427_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expires_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 16, 49, 47, 272770)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manag_level',
            field=models.CharField(max_length=255),
        ),
    ]
